"""
Agentic pipeline — two agents, one shared local model, two phases.

    candidate papers (~20)
            |
            v
      Reviewer Agent  <-- build_review_crew() / kicked off in main.py
            |
      picks 5 ids + reasons  (ReviewerSelection, via output_pydantic)
            |
            v
   select_papers()  <-- plain Python, narrows the candidate list down
            |             to just the 5 the Reviewer picked
            v
       Writer Agent  <-- build_write_crew() / kicked off in main.py
            |             sees ONLY those 5 papers' title/abstract/URL
            v
   5 blog entries  (DigestOutput, via output_pydantic)

Each phase is its own single-task `Crew`. This is deliberate, not
incidental: the Writer's prompt has to be *built from the Reviewer's
output*, and a Task's description is fixed Python text at construction
time — there's no way to hand a Task data it doesn't have yet. Splitting
into two crews lets ordinary Python sit between the two agent calls to do
that narrowing, which is exactly what `select_papers()` does. `main.py`
runs both phases, one `.kickoff()` each, back to back.

Design choices worth noting:

1. Both agents share a single `LLM` instance pointed at the same Ollama
   model, passed in from `main.py` and reused across both phases and every
   category. Ollama can only keep so much in an 8GB card at once — if the
   Reviewer and Writer used *different* models, Ollama would unload/reload
   between every call, which is slow and can transiently spike VRAM during
   the swap. One resident model avoids that entirely.

2. Both tasks use `output_pydantic` instead of asking the LLM to return
   free-text Markdown. Small local models are noticeably less reliable at
   following loose formatting instructions than GPT-4-class models, so we
   ask CrewAI to validate/parse structured JSON for us rather than
   regex-scraping prose later. The Reviewer's structured `id` list is also
   what makes `select_papers()` possible in the first place.

3. Paper JSON is embedded directly into each Task's `description` with an
   f-string, not passed through `crew.kickoff(inputs=...)`. CrewAI's
   inputs-templating does a naive `{key}` substitution, which breaks on the
   literal curly braces inside JSON — so we render the prompt ourselves.

4. The Writer task has no `context=[...]`. That parameter forwards a prior
   task's output *within the same crew*, but the Writer now lives in a
   separate `Crew` from the Reviewer, and its prompt is already built from
   the Reviewer's decision (via `select_papers()`) before the Writer's
   `Task` even exists — there's nothing left for `context` to add.
"""
from __future__ import annotations

import json
from typing import Dict, List, Optional

from crewai import Agent, Crew, LLM, Process, Task
from pydantic import BaseModel, Field

from config import (
    REVIEWER_ABSTRACT_CHARS,
    WRITER_ABSTRACT_CHARS,
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    OLLAMA_TEMPERATURE,
)


# ---------------------------------------------------------------------------
# Structured outputs
# ---------------------------------------------------------------------------
class SelectedPaper(BaseModel):
    id: str
    reason: str


class ReviewerSelection(BaseModel):
    selected_papers: List[SelectedPaper]


# Intermediate draft generated by LLM (No links or reasons requested from LLM)
class LLMDraftEntry(BaseModel):
    id: str = Field(
        description="The exact paper ID provided in the input JSON (e.g. '2608.28025v1'). Do NOT change or renumber this ID."
    )
    title: str = Field(description="An engaging blog headline for the paper.")
    paragraph: str = Field(description="The newsletter summary paragraph.")


class WriterOutput(BaseModel):
    articles: List[LLMDraftEntry]


# Final fully-hydrated structure (Produced by Python post-processing)
class BlogEntry(BaseModel):
    id: str
    reason: str
    title: str
    paragraph: str
    link: str
    # Metadata below comes straight from fetcher.py's paper dicts, never
    # from the LLM — same "Python owns ground truth" principle as `link`.
    # New fields default sensibly so old cached JSON / older code that
    # constructs a BlogEntry without them still works.
    authors: List[str] = Field(default_factory=list)
    published: str = ""
    source: str = ""
    doi: str = ""


class DigestOutput(BaseModel):
    entries: List[BlogEntry]


# ---------------------------------------------------------------------------
# LLM
# ---------------------------------------------------------------------------
def get_local_llm() -> LLM:
    return LLM(
        model=OLLAMA_MODEL,
        base_url=OLLAMA_BASE_URL,
        temperature=OLLAMA_TEMPERATURE,
    )


def _papers_for_prompt(papers: List[Dict],
        abstract_chars: int,) -> str:
    trimmed = [
        {
            "id": p["id"],
            "title": p["title"],
            "abstract": p["abstract"][:abstract_chars],
        }
        for p in papers
    ]
    return json.dumps(trimmed, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Agents
# ---------------------------------------------------------------------------
def _build_reviewer(llm: LLM, category: str) -> Agent:
    return Agent(
        role="Senior Science Editor",
        goal=(
            f"Select the 5 most impactful, novel, or broadly interesting new "
            f"{category} papers from this week's preprint feed."
        ),
        backstory=(
            "You've spent 15 years as an editor at a respected science "
            "magazine. You have a nose for genuinely important results and "
            "no patience for incremental, over-hyped, or narrow findings."
        ),
        llm=llm,
        verbose=True,
        allow_delegation=False,
    )


def _build_writer(llm: LLM) -> Agent:
    return Agent(
        role="Science Writer",
        goal=(
            "Turn scientific abstracts into short, accurate, engaging "
            "science-news summaries for curious non-specialist readers. "
            "Prioritize factual accuracy and clarity over hype."
        ),
        backstory=(
            "You are a careful science journalist. You explain research "
            "clearly without oversimplifying it, exaggerating its importance, "
            "or inventing claims that are not supported by the source."
        ),
        llm=llm,
        verbose=True,
        allow_delegation=False,
    )


# ---------------------------------------------------------------------------
# Tasks
# ---------------------------------------------------------------------------
def _build_review_task(papers: List[Dict], category: str, reviewer: Agent) -> Task:
    papers_json = _papers_for_prompt(papers,REVIEWER_ABSTRACT_CHARS)
    return Task(
        description=(
            f"Here are {len(papers)} recent {category} preprints as a JSON "
            f"array of objects with 'id', 'title', and 'abstract':\n\n"
            f"{papers_json}\n\n"
            "Pick exactly 5 papers that are most scientifically impactful, "
            "novel, or broadly interesting to an intelligent general "
            "audience. Give a one-sentence reason for each pick. Only use "
            "ids that appear in the JSON above — never invent one."
        ),
        expected_output=(
            "A JSON object with a 'selected_papers' list of exactly 5 "
            "items, each with 'id' and 'reason'."
        ),
        agent=reviewer,
        output_pydantic=ReviewerSelection,
    )


def _build_write_task(
    selected_papers: List[Dict],
    category: str,
    writer: Agent
) -> Task:
    """Build the Writer's task from the already-selected papers."""

    papers_json = _papers_for_prompt(
        selected_papers,
        WRITER_ABSTRACT_CHARS
    )

    n = len(selected_papers)

    return Task(
        description=(
            f"The Reviewer has already chosen the following {n} {category} "
            "papers as this week's most interesting picks.\n\n"

            "Here are the papers you MUST write about:\n\n"
            f"{papers_json}\n\n"

            f"Write one clear, engaging, accurate paragraph of roughly "
            f"100-140 words for EACH of these {n} papers, suitable for "
            "a general-interest science blog.\n\n"

            "Writing rules:\n"
            "- Describe what the researchers actually did and found.\n"
            "- Use only information supported by the supplied abstract.\n"
            "- Do not invent results, applications, causes, benefits, or future implications.\n"
            "- Do not claim that a method improves, enables, proves, or will lead "
            "to something unless the abstract explicitly supports that claim.\n"
            "- Avoid hype such as 'groundbreaking', 'revolutionary', or 'game-changing'.\n"
            "- When discussing importance, explain the scientific significance "
            "of the demonstrated result rather than predicting future outcomes.\n"
            "- Avoid unexplained jargon where possible.\n"
            "- Use the exact paper ID provided in the input.\n"
            "- Do not invent or modify paper IDs.\n"
            "- Do not discuss any paper other than the ones listed above.\n"
        ),
        expected_output=(
            f"A JSON object with an 'articles' list containing exactly {n} "
            "items. Each item must contain the exact paper 'id', an engaging "
            "'title', and a 'paragraph'. Do not invent paper IDs."
        ),
        agent=writer,
        output_pydantic=WriterOutput,
    )


# ---------------------------------------------------------------------------
# Reviewer -> Writer handoff & Metadata Hydration (plain Python)
# ---------------------------------------------------------------------------

def select_papers(papers: List[Dict], selection: ReviewerSelection) -> List[Dict]:
    """Narrows the original candidate list down to the Reviewer's picks

    and attaches the Reviewer's 'reason' to each paper dictionary.
    """
    by_id = {p["id"]: p for p in papers}
    selected = []
    for pick in selection.selected_papers:
        paper = by_id.get(pick.id)
        if paper is None:
            print(f"  ! reviewer picked an id not in the candidate set, skipping: {pick.id!r}")
            continue

        # Copy paper dict and attach the reviewer's reason
        paper_copy = dict(paper)
        paper_copy["reason"] = pick.reason
        selected.append(paper_copy)
    return selected

def hydrate_digest_output(writer_output: WriterOutput, selected_papers: List[Dict]) -> DigestOutput:
    """Merges LLM draft articles back with Python ground-truth metadata (URL, Reason, ID, authors, source, etc.)."""
    by_id = {p["id"]: p for p in selected_papers}
    entries = []

    for draft in writer_output.articles:
        paper = by_id.get(draft.id)
        if not paper:
            print(f"  ! Warning: could not match draft ID '{draft.id}' back to selected papers.")
            continue

        entries.append(
            BlogEntry(
                id=paper["id"],
                reason=paper.get("reason", ""),
                title=draft.title,
                paragraph=draft.paragraph,
                link=paper.get("url") or paper.get("doi") or "",
                authors=paper.get("authors", []),          # <-- ensure this line exists
                published=paper.get("published", ""),
                source=paper.get("source", ""),
                doi=paper.get("doi", ""),
            )
        )

    return DigestOutput(entries=entries)

# ---------------------------------------------------------------------------
# Crews — one per phase
# ---------------------------------------------------------------------------
def build_review_crew(papers: List[Dict], category: str, llm: Optional[LLM] = None) -> Crew:
    """Phase 1: the Reviewer looks at every candidate and picks 5."""
    if not papers:
        raise ValueError("build_review_crew() called with no papers to review")

    llm = llm or get_local_llm()
    reviewer = _build_reviewer(llm, category)
    review_task = _build_review_task(papers, category, reviewer)

    return Crew(
        agents=[reviewer],
        tasks=[review_task],
        process=Process.sequential,
        verbose=True,
    )


def build_write_crew(selected_papers: List[Dict], category: str, llm: Optional[LLM] = None) -> Crew:
    """Phase 2: the Writer drafts blog entries for the 5 selected papers
    only. Call `select_papers()` to produce `selected_papers` first.
    """
    if not selected_papers:
        raise ValueError("build_write_crew() called with no selected papers")

    llm = llm or get_local_llm()
    writer = _build_writer(llm)
    write_task = _build_write_task(selected_papers, category, writer)

    return Crew(
        agents=[writer],
        tasks=[write_task],
        process=Process.sequential,
        verbose=True,
    )